language: php

php:
  - 5.6
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  matrix:
    - DB=mysql
  global:
    - PHPUNIT=3.7.38

matrix:
  fast_finish: true

before_install:
  - echo "memory_limit=384M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer require "phpunit/phpunit=$PHPUNIT"
  - echo "require_once 'vendors/autoload.php';" >> app/Config/bootstrap.php
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test CHARACTER SET utf8 COLLATE utf8_general_ci;'; fi"
  - chmod -R 777 ./app/tmp
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]] ; then echo "yes" | pecl install apcu-5.1.3 || true; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]] ; then echo "yes" | pecl install apcu-4.0.11 || true; fi
  - echo -e "extension = apcu.so\napc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
        public \$default = array(
            'persistent' => false,
            'datasource' => 'Database/Mysql',
            'host' => '127.0.0.1',
            'login' => 'travis',
            'password' => '',
            'database' => 'cakephp_test',
            'prefix' => '',
            'encoding' => 'utf8'
        );
        public \$test = array(
            'persistent' => false,
            'datasource' => 'Database/Mysql',
            'host' => '127.0.0.1',
            'login' => 'travis',
            'password' => '',
            'database' => 'cakephp_test',
            'prefix' => '',
            'encoding' => 'utf8'
        );
    }" > app/Config/database.php
  - echo "<?php
    $config['CakeInstaller'] = [
        'installerCommands' => [
            'setsecurkey',
            'createsymlinks',
            'install',
        ],
        'installTasks' => [
            'setsecurkey',
            'createsymlinks',
        ]
    ];" > app/Config/cakeinstaller.php
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<phpunit>
<filter>
    <whitelist>
        <exclude>
            <directory suffix=\".php\">Vendor</directory>
            <directory suffix=\".php\">Plugin/*/Vendor</directory>
        </exclude>
    </whitelist>
</filter>
</phpunit>" > app/phpunit.xml
  - sed -i -r "s/(Configure::write\('debug', )[0-2]{1}(\);)/\11\2/i" ./app/Config/core.php
  - if [ -f "./app/Console/cake" ]; then ./app/Console/cake CakeInstaller install --app $(cd ./app; pwd); fi

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then ./app/Console/cake test app AllApp --stderr --app $(cd ./app; pwd); if [ \"$?\" -gt 0 ]; then exit 1; fi; fi"

notifications:
  email: false
