language: php

php:
  - 5.6
  - 7.1

env:
  matrix:
    - DB=mysql
  global:
    - PHPUNIT=3.7.38

matrix:
  fast_finish: true

before_script:
  - composer require "phpunit/phpunit=$PHPUNIT"
  - ln -sr vendor/phpunit/phpunit/PHPUnit app/Vendor/PHPUnit
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test CHARACTER SET utf8 COLLATE utf8_general_ci;'; fi"
  - chmod -R 777 ./app/tmp
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]] ; then echo "yes" | pecl install apcu-5.1.3 || true; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]] ; then echo "yes" | pecl install apcu-4.0.11 || true; fi
  - echo -e "extension = apcu.so\napc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '127.0.0.1',
      'login' => 'travis',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    public \$test = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '127.0.0.1',
      'login' => 'travis',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > app/Config/database.php
  - sed -i -r "s/(Configure::write\('debug', )[0-2]{1}(\);)/\11\2/i" ./app/Config/core.php
  - sed -i -r "s/(Configure::write\('Security\.salt', ')[0-9a-z]+('\);)/\1d1c97797953ed55c54ba6037158d2b0c3bf21471\2/i" ./app/Config/core.php
  - sed -i -r "s/(Configure::write\('Security\.cipherSeed', ')[0-9]+('\);)/\118424236609940891573169173047\2/i" ./app/Config/core.php

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then cd ./app; ./Console/cake test app AllApp --stderr; if [ \"$?\" -gt 0 ]; then exit 1; fi; fi"

notifications:
  email: false
