language: php

php:
  - 5.6
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  matrix:
    - DB=mysql
  global:
    - TESTARG="app AllApp --stderr --app $(cd ./app; pwd)"
    - PHPUNIT=3.7.38

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1

before_script:
  - composer require "phpunit/phpunit=$PHPUNIT"
  - echo "require_once 'vendors/autoload.php';" >> app/Config/bootstrap.php
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test CHARACTER SET utf8 COLLATE utf8_general_ci;'; fi"
  - chmod -R 777 ./app/tmp
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require 'cakephp/cakephp-codesniffer:1.*'; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendors/bin/phpcs --config-set installed_paths vendors/cakephp/cakephp-codesniffer; fi"
  - sh -c "if [ '$CODECOVERAGE' == '1' ]; then TESTARG="$TESTARG --coverage-clover clover.xml"; fi;"
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]] ; then echo "yes" | pecl install apcu-5.1.3 || true; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]] ; then echo "yes" | pecl install apcu-4.0.11 || true; fi
  - echo -e "extension = apcu.so\napc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '127.0.0.1',
      'login' => 'travis',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    public \$test = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '127.0.0.1',
      'login' => 'travis',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > app/Config/database.php
  - echo "<?php
    $config['CakeInstaller'] = [
        'installerCommands' => [
            'setsecurkey',
            'createsymlinks',
            'install',
        ],
        'installTasks' => [
            'setsecurkey',
            'createsymlinks',
        ]
    ];" > app/Config/cakeinstaller.php
  - echo "Installed" > app/tmp/installer/installed.txt
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <phpunit>
        <php>
            <ini name=\"memory_limit\" value=\"384M\" />
        </php>
        <filter>
            <whitelist>
                <exclude>
                    <directory suffix=\".php\">Vendor</directory>
                    <directory suffix=\".php\">Plugin</directory>
                </exclude>
            </whitelist>
        </filter>
    </phpunit>" > app/phpunit.xml
  - if [ -f "./app/Console/cake" ]; then ./app/Console/cake CakeInstaller install --app $(cd ./app; pwd); fi

script:
  - sh -c "if [ '$PHPCS' = '1' ]; then vendors/bin/phpcs -p --extensions=php --standard=CakePHP ./app; fi;"
  - sh -c "if [ '$PHPCS' != '1' ]; then ./app/Console/cake test $TESTARG; if [ \"$?\" -gt 0 ]; then exit 1; fi; fi"

after_success:
  - if [ -d "./app" ]; then cd ./app; fi
  - if [ '$CODECOVERAGE' == '1' ]; then wget -O codecov.sh https://codecov.io/bash; bash codecov.sh; fi

notifications:
  email: false
